USE HotelBookingDB_LastStand_11;
GO

PRINT N'=== BẮT ĐẦU KIỂM TRA VÀ SỬA LỖI CỘT KHACH_SAN_ID ===';
GO

-- 1. Kiểm tra và sửa bảng BOOKING
PRINT N'1. Kiểm tra bảng BOOKING...';
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'BOOKING' AND COLUMN_NAME = 'khach_san_id')
BEGIN
    ALTER TABLE BOOKING ADD khach_san_id INT NULL;
    UPDATE BOOKING SET khach_san_id = 1;
    ALTER TABLE BOOKING ALTER COLUMN khach_san_id INT NOT NULL;
    PRINT N'   ✓ Đã thêm cột khach_san_id vào bảng BOOKING';
END
ELSE
BEGIN
    PRINT N'   ✓ Bảng BOOKING đã có cột khach_san_id';
    UPDATE BOOKING SET khach_san_id = 1 WHERE khach_san_id IS NULL;
END
GO

-- 2. Kiểm tra và sửa bảng ROOM
PRINT N'2. Kiểm tra bảng ROOM...';
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'ROOM' AND COLUMN_NAME = 'khach_san_id')
BEGIN
    ALTER TABLE ROOM ADD khach_san_id INT NULL;
    UPDATE ROOM SET khach_san_id = 1;
    ALTER TABLE ROOM ALTER COLUMN khach_san_id INT NOT NULL;
    PRINT N'   ✓ Đã thêm cột khach_san_id vào bảng ROOM';
END
ELSE
BEGIN
    PRINT N'   ✓ Bảng ROOM đã có cột khach_san_id';
    UPDATE ROOM SET khach_san_id = 1 WHERE khach_san_id IS NULL;
END
GO

-- 3. Kiểm tra và sửa bảng INVENTORY_MANAGEMENT
PRINT N'3. Kiểm tra bảng INVENTORY_MANAGEMENT...';
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'INVENTORY_MANAGEMENT' AND COLUMN_NAME = 'khach_san_id')
BEGIN
    ALTER TABLE INVENTORY_MANAGEMENT ADD khach_san_id INT NULL;
    UPDATE INVENTORY_MANAGEMENT SET khach_san_id = 1;
    ALTER TABLE INVENTORY_MANAGEMENT ALTER COLUMN khach_san_id INT NOT NULL;
    PRINT N'   ✓ Đã thêm cột khach_san_id vào bảng INVENTORY_MANAGEMENT';
END
ELSE
BEGIN
    PRINT N'   ✓ Bảng INVENTORY_MANAGEMENT đã có cột khach_san_id';
    UPDATE INVENTORY_MANAGEMENT SET khach_san_id = 1 WHERE khach_san_id IS NULL;
END
GO

-- 4. Kiểm tra và sửa bảng INVENTORY_TRANSACTION
PRINT N'4. Kiểm tra bảng INVENTORY_TRANSACTION...';
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'INVENTORY_TRANSACTION' AND COLUMN_NAME = 'khach_san_id')
BEGIN
    ALTER TABLE INVENTORY_TRANSACTION ADD khach_san_id INT NULL;
    UPDATE INVENTORY_TRANSACTION SET khach_san_id = 1;
    ALTER TABLE INVENTORY_TRANSACTION ALTER COLUMN khach_san_id INT NOT NULL;
    PRINT N'   ✓ Đã thêm cột khach_san_id vào bảng INVENTORY_TRANSACTION';
END
ELSE
BEGIN
    PRINT N'   ✓ Bảng INVENTORY_TRANSACTION đã có cột khach_san_id';
    UPDATE INVENTORY_TRANSACTION SET khach_san_id = 1 WHERE khach_san_id IS NULL;
END
GO

-- 5. Kiểm tra và sửa bảng EVENT_CALENDAR
PRINT N'5. Kiểm tra bảng EVENT_CALENDAR...';
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'EVENT_CALENDAR' AND COLUMN_NAME = 'khach_san_id')
BEGIN
    ALTER TABLE EVENT_CALENDAR ADD khach_san_id INT NULL;
    UPDATE EVENT_CALENDAR SET khach_san_id = 1;
    ALTER TABLE EVENT_CALENDAR ALTER COLUMN khach_san_id INT NOT NULL;
    PRINT N'   ✓ Đã thêm cột khach_san_id vào bảng EVENT_CALENDAR';
END
ELSE
BEGIN
    PRINT N'   ✓ Bảng EVENT_CALENDAR đã có cột khach_san_id';
    UPDATE EVENT_CALENDAR SET khach_san_id = 1 WHERE khach_san_id IS NULL;
END
GO

PRINT N'=== THÊM FOREIGN KEY CONSTRAINTS ===';
GO

-- Thêm foreign key constraints cho tất cả các bảng
-- BOOKING
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
               WHERE CONSTRAINT_NAME = 'FK_BOOKING_HOTEL' AND TABLE_NAME = 'BOOKING')
BEGIN
    ALTER TABLE BOOKING ADD CONSTRAINT FK_BOOKING_HOTEL 
    FOREIGN KEY (khach_san_id) REFERENCES HOTEL(id);
    PRINT N'   ✓ Đã thêm FK_BOOKING_HOTEL';
END
ELSE
    PRINT N'   ✓ FK_BOOKING_HOTEL đã tồn tại';
GO

-- ROOM
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
               WHERE CONSTRAINT_NAME = 'FK_ROOM_HOTEL' AND TABLE_NAME = 'ROOM')
BEGIN
    ALTER TABLE ROOM ADD CONSTRAINT FK_ROOM_HOTEL 
    FOREIGN KEY (khach_san_id) REFERENCES HOTEL(id);
    PRINT N'   ✓ Đã thêm FK_ROOM_HOTEL';
END
ELSE
    PRINT N'   ✓ FK_ROOM_HOTEL đã tồn tại';
GO

-- INVENTORY_MANAGEMENT
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
               WHERE CONSTRAINT_NAME = 'FK_INVENTORY_MANAGEMENT_HOTEL' AND TABLE_NAME = 'INVENTORY_MANAGEMENT')
BEGIN
    ALTER TABLE INVENTORY_MANAGEMENT ADD CONSTRAINT FK_INVENTORY_MANAGEMENT_HOTEL 
    FOREIGN KEY (khach_san_id) REFERENCES HOTEL(id);
    PRINT N'   ✓ Đã thêm FK_INVENTORY_MANAGEMENT_HOTEL';
END
ELSE
    PRINT N'   ✓ FK_INVENTORY_MANAGEMENT_HOTEL đã tồn tại';
GO

-- INVENTORY_TRANSACTION
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
               WHERE CONSTRAINT_NAME = 'FK_INVENTORY_TRANSACTION_HOTEL' AND TABLE_NAME = 'INVENTORY_TRANSACTION')
BEGIN
    ALTER TABLE INVENTORY_TRANSACTION ADD CONSTRAINT FK_INVENTORY_TRANSACTION_HOTEL 
    FOREIGN KEY (khach_san_id) REFERENCES HOTEL(id);
    PRINT N'   ✓ Đã thêm FK_INVENTORY_TRANSACTION_HOTEL';
END
ELSE
    PRINT N'   ✓ FK_INVENTORY_TRANSACTION_HOTEL đã tồn tại';
GO

-- EVENT_CALENDAR
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
               WHERE CONSTRAINT_NAME = 'FK_EVENT_CALENDAR_HOTEL' AND TABLE_NAME = 'EVENT_CALENDAR')
BEGIN
    ALTER TABLE EVENT_CALENDAR ADD CONSTRAINT FK_EVENT_CALENDAR_HOTEL 
    FOREIGN KEY (khach_san_id) REFERENCES HOTEL(id);
    PRINT N'   ✓ Đã thêm FK_EVENT_CALENDAR_HOTEL';
END
ELSE
    PRINT N'   ✓ FK_EVENT_CALENDAR_HOTEL đã tồn tại';
GO

PRINT N'=== TÓM TẮT KẾT QUẢ ===';
PRINT N'Kiểm tra các bảng đã được cập nhật:';

-- Hiển thị tóm tắt các cột khach_san_id
SELECT 
    TABLE_NAME as 'Bảng',
    CASE WHEN COLUMN_NAME IS NOT NULL THEN 'CÓ' ELSE 'KHÔNG' END as 'Có cột khach_san_id'
FROM (
    SELECT 'BOOKING' as TABLE_NAME
    UNION SELECT 'ROOM'
    UNION SELECT 'INVENTORY_MANAGEMENT'
    UNION SELECT 'INVENTORY_TRANSACTION'
    UNION SELECT 'EVENT_CALENDAR'
) tables
LEFT JOIN INFORMATION_SCHEMA.COLUMNS cols 
    ON tables.TABLE_NAME = cols.TABLE_NAME 
    AND cols.COLUMN_NAME = 'khach_san_id'
ORDER BY tables.TABLE_NAME;
GO

PRINT N'=== HOÀN THÀNH ===';
PRINT N'Tất cả các bảng đã được kiểm tra và cập nhật cột khach_san_id.';
PRINT N'Bây giờ bạn có thể chạy lại ứng dụng Spring Boot.';